// Offline PDF generation utility
// Uses browser's print functionality for true PDF export
import type { WorkflowStep } from "@/types/workflow";

export interface WorkflowStepData {
  id: string;
  title: string;
  description: string;
  duration: string;
  effort: string;
  safetyNote?: string;
  materials?: string[];
}

export function generateStepPDF(step: WorkflowStep, stepNumber: number): void {
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Step ${stepNumber}: ${step.title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          color: #1a1a1a;
          line-height: 1.6;
        }
        .header {
          border-bottom: 2px solid #0d9488;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .step-number {
          display: inline-block;
          background: #0d9488;
          color: white;
          width: 40px;
          height: 40px;
          border-radius: 50%;
          text-align: center;
          line-height: 40px;
          font-weight: bold;
          margin-right: 15px;
        }
        h1 { 
          display: inline-block;
          font-size: 24px;
          vertical-align: middle;
        }
        .meta {
          display: flex;
          gap: 30px;
          margin: 20px 0;
          padding: 15px;
          background: #f8fafc;
          border-radius: 8px;
        }
        .meta-item {
          text-align: center;
        }
        .meta-label {
          font-size: 12px;
          color: #64748b;
          text-transform: uppercase;
        }
        .meta-value {
          font-size: 18px;
          font-weight: 600;
          color: #0d9488;
        }
        .section {
          margin-bottom: 25px;
        }
        .section-title {
          font-size: 14px;
          text-transform: uppercase;
          color: #64748b;
          margin-bottom: 8px;
        }
        .description {
          font-size: 16px;
          color: #374151;
        }
        .safety-note {
          background: #fef3c7;
          border-left: 4px solid #f59e0b;
          padding: 15px;
          border-radius: 0 8px 8px 0;
        }
        .safety-note h3 {
          color: #b45309;
          font-size: 14px;
          margin-bottom: 5px;
        }
        .materials {
          display: flex;
          flex-wrap: wrap;
          gap: 8px;
        }
        .material-tag {
          background: #e0f2fe;
          color: #0369a1;
          padding: 5px 12px;
          border-radius: 20px;
          font-size: 14px;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          font-size: 12px;
          color: #9ca3af;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <span class="step-number">${stepNumber}</span>
        <h1>${step.title}</h1>
      </div>
      
      <div class="meta">
        <div class="meta-item">
          <div class="meta-label">Duration</div>
          <div class="meta-value">${step.duration}</div>
        </div>
        <div class="meta-item">
          <div class="meta-label">Effort Level</div>
          <div class="meta-value">${step.effort}</div>
        </div>
      </div>
      
      <div class="section">
        <div class="section-title">Description</div>
        <p class="description">${step.description}</p>
      </div>
      
      ${step.safetyNote ? `
        <div class="section">
          <div class="safety-note">
            <h3>&#9888;&#65039; Safety Note</h3>
            <p>${step.safetyNote}</p>
          </div>
        </div>
      ` : ''}
      
      ${step.materials && step.materials.length > 0 ? `
        <div class="section">
          <div class="section-title">Required Materials</div>
          <div class="materials">
            ${step.materials.map(m => `<span class="material-tag">${m}</span>`).join('')}
          </div>
        </div>
      ` : ''}
      
      <div class="footer">
        Generated by Smart Design Assistant &bull; ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

export function generateFullWorkflowPDF(steps: WorkflowStep[], designName: string): void {
  const stepsHTML = steps.map((step, index) => `
    <div class="step" style="page-break-inside: avoid;">
      <div class="step-header">
        <span class="step-number">${index + 1}</span>
        <h2>${step.title}</h2>
        <span class="duration">${step.duration}</span>
        <span class="effort ${step.effort.toLowerCase()}">${step.effort}</span>
      </div>
      <p class="step-description">${step.description}</p>
      ${step.safetyNote ? `
        <div class="safety-note">
          <strong>&#9888;&#65039; Safety:</strong> ${step.safetyNote}
        </div>
      ` : ''}
    </div>
  `).join('');

  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${designName} - Manufacturing Workflow</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 40px;
          color: #1a1a1a;
          line-height: 1.6;
        }
        .header {
          text-align: center;
          border-bottom: 2px solid #0d9488;
          padding-bottom: 30px;
          margin-bottom: 30px;
        }
        .header h1 {
          font-size: 28px;
          margin-bottom: 5px;
        }
        .header p {
          color: #64748b;
        }
        .step {
          margin-bottom: 25px;
          padding: 20px;
          border: 1px solid #e5e7eb;
          border-radius: 12px;
        }
        .step-header {
          display: flex;
          align-items: center;
          gap: 15px;
          margin-bottom: 15px;
        }
        .step-number {
          background: #0d9488;
          color: white;
          width: 32px;
          height: 32px;
          border-radius: 50%;
          text-align: center;
          line-height: 32px;
          font-weight: bold;
          font-size: 14px;
        }
        .step-header h2 {
          flex: 1;
          font-size: 18px;
        }
        .duration {
          font-size: 14px;
          color: #64748b;
        }
        .effort {
          font-size: 12px;
          padding: 4px 12px;
          border-radius: 20px;
          font-weight: 500;
        }
        .effort.low { background: #dcfce7; color: #166534; }
        .effort.medium { background: #fef3c7; color: #b45309; }
        .effort.high { background: #fee2e2; color: #b91c1c; }
        .step-description {
          color: #4b5563;
        }
        .safety-note {
          margin-top: 15px;
          padding: 12px;
          background: #fef3c7;
          border-radius: 8px;
          font-size: 14px;
          color: #92400e;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          font-size: 12px;
          color: #9ca3af;
        }
        @media print {
          .step { break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${designName}</h1>
        <p>Manufacturing Workflow - ${steps.length} Steps</p>
      </div>
      
      ${stepsHTML}
      
      <div class="footer">
        Generated by Smart Design Assistant &bull; ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}

